name: Build

on:
  push:
    branches-ignore:
      - "!*-oryx"
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: "${{ github.ref }}"
          fetch-depth: 0
          submodules: recursive

      - name: Configure account
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build
        run: make all

      - name: Commit and push
        run: make commit-build-dir

      - name: Echo environment data
        id: env
        run: make -s echo-env >> "$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: "${{ steps.env.outputs.my_keyboard }}_${{ steps.env.outputs.rev_meta_title }}"
          compression-level: 9
          path: |
            build/keyboard.json
            build/keymap.bin
            build/keymap.json
            build/keymap.yml
            build/keymap.svg

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ steps.env.outputs.timestamp }}" \
            --target "${{ github.ref }}" \
            --title "${{ steps.env.outputs.my_keyboard }} ${{ steps.env.outputs.rev_meta_title }} (${{ steps.env.outputs.timestamp }})" \
            --generate-notes
          gh release upload "${{ steps.env.outputs.timestamp }}" \
            build/keymap.bin \
            build/keymap.svg
